[dev]
  targetPort = 5173

[build]
  command = "pnpm build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  status = 200
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
